DataType: SQLITE

Modules:
  Nickname:
    Enabled: true
    Reset:
      - "off"
      - "reset"
  Fly:
    Enabled: true
  GameMode:
    Enabled: true
  Teleport:
    Enabled: true
  Hat:
    Enabled: true
  Shuffle:
    Enabled: true
  Rotate:
    Enabled: true
  ClearInventory:
    Enabled: true
  Speed:
    Enabled: true