DataType: SQLITE

Modules:
  Nickname:
    Enabled: true
    Reset:
      - "off"
      - "reset"
  Fly:
    Enabled: true
  GameMode:
    Enabled: true
  Teleport:
    Enabled: true
  Hat:
    Enabled: true
  Shuffle:
    Enabled: true
  Rotate:
    Enabled: true
  ClearInventory:
    Enabled: true
  Speed:
    Enabled: true
  Tell:
    Enabled: true
  CrossTeleport:
    Enabled: true
  Sudo:
    Enabled: true
  Spawn:
    Enabled: true
    onJoin: true
    onRespawn: true
    onVoid: true
    location: ""