name: Mercury
version: '${project.version}'
main: ir.ciph3r.mercury.Mercury
api-version: 1.13
authors: [ Ciph3r ]
description: A core plugin made to make life easier

commands:
  nickname:
    usage: /<command>
  fly:
    usage: /<command>
  gamemode:
    usage: /<command>
    aliases: [gmc, gms, gma, gmsp]